name: professional_dark_personal_portfolio
description: Welcome to my personal portfolio


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  
  animated_text_kit: ^4.2.2
  flutter_animate: ^3.1.0
  flutter_animated_button: ^2.0.3
  fluttertoast: ^8.1.3
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.9
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  simple_circular_progress_bar: ^1.0.2
  firebase_core: ^2.5.0
  countup: ^0.1.4
  liquid_progress_indicator: ^0.4.0
  cloud_firestore: ^4.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true